function path=graddown(goal,start,Ug)
path=[start];
i=1;
while path(end,1)~=goal(1) || path(end,2)~=goal(2)
    node=path(end,:);
    i=i+1;
    if node(1)==112
        1;
    end
    temp=[node(1)-1,node(2); ...
        node(1)+1,node(2); ...
        node(1),node(2)-1; ...
        node(1),node(2)+1; ...
        node(1)-1,node(2)-1; ...
        node(1)-1,node(2)+1; ...
        node(1)+1,node(2)-1; ...
        node(1)+1,node(2)+1; ...
        ];
    temp_T=[Ug(node(1)-1,node(2)); ...
        Ug(node(1)+1,node(2)); ...
        Ug(node(1),node(2)-1); ...
        Ug(node(1),node(2)+1); ...
        Ug(node(1)-1,node(2)-1); ...
        Ug(node(1)-1,node(2)+1); ...
        Ug(node(1)+1,node(2)-1); ...
        Ug(node(1)+1,node(2)+1); ...
        ];
    index_temp=find(temp_T==min(temp_T));
    index=index_temp(1);
    path=[path;temp(index,:)];
    if i>1000
        break
    end
end
end